// backend/src/services/export.service.ts
import { marked } from 'marked';

type ExportFormat = 'pdf' | 'docx' | 'md' | 'txt';

export interface ExportResult {
  buffer: Buffer;
  mimeType: string;
  filename: string;
}

// ── Main export dispatcher ────────────────────────────────────────────────────

export async function exportSummary(
  markdownContent: string,
  documentName: string,
  format: ExportFormat,
  mode: string
): Promise<ExportResult> {
  const baseName = sanitizeFilename(documentName);
  const label = mode.replace(/_/g, '-');

  switch (format) {
    case 'pdf':
      return exportAsPdf(markdownContent, documentName, `${baseName}_${label}.pdf`);
    case 'docx':
      return exportAsDocx(markdownContent, documentName, `${baseName}_${label}.docx`);
    case 'md':
      return exportAsMarkdown(markdownContent, `${baseName}_${label}.md`);
    case 'txt':
      return exportAsText(markdownContent, `${baseName}_${label}.txt`);
    default:
      throw new Error(`Unsupported export format: ${format}`);
  }
}

// ── PDF export ────────────────────────────────────────────────────────────────

async function exportAsPdf(
  markdown: string,
  documentName: string,
  filename: string
): Promise<ExportResult> {
  const pdfmake = await import('pdfmake/build/pdfmake');
  const pdfFonts = await import('pdfmake/build/vfs_fonts');

  (pdfmake as any).vfs = (pdfFonts as any).pdfMake?.vfs;

  const docDefinition = markdownToPdfDefinition(markdown, documentName);
  const pdfDoc = (pdfmake as any).createPdf(docDefinition);

  const buffer = await new Promise<Buffer>((resolve, reject) => {
    pdfDoc.getBuffer((buf: Uint8Array) => {
      resolve(Buffer.from(buf));
    });
    // Timeout fallback
    setTimeout(() => reject(new Error('PDF generation timeout')), 30_000);
  });

  return {
    buffer,
    mimeType: 'application/pdf',
    filename,
  };
}

function markdownToPdfDefinition(markdown: string, title: string) {
  const lines = markdown.split('\n');
  const content: object[] = [
    { text: title, style: 'docTitle', margin: [0, 0, 0, 20] },
    { text: `Generated by StudySummarizer · ${new Date().toLocaleDateString()}`, style: 'subtitle', margin: [0, 0, 0, 30] },
  ];

  let currentList: string[] = [];

  function flushList() {
    if (currentList.length > 0) {
      content.push({ ul: currentList, margin: [0, 0, 0, 10] });
      currentList = [];
    }
  }

  for (const line of lines) {
    if (line.startsWith('## ')) {
      flushList();
      content.push({ text: line.slice(3), style: 'h2', margin: [0, 15, 0, 6] });
    } else if (line.startsWith('### ')) {
      flushList();
      content.push({ text: line.slice(4), style: 'h3', margin: [0, 10, 0, 4] });
    } else if (line.startsWith('# ')) {
      flushList();
      content.push({ text: line.slice(2), style: 'h1', margin: [0, 20, 0, 8] });
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      currentList.push(line.slice(2));
    } else if (line.trim()) {
      flushList();
      content.push({ text: parseInlineMarkdown(line), style: 'body', margin: [0, 0, 0, 6] });
    } else {
      flushList();
    }
  }
  flushList();

  return {
    content,
    styles: {
      docTitle: { fontSize: 20, bold: true, color: '#1a1a2e' },
      subtitle: { fontSize: 10, color: '#666' },
      h1: { fontSize: 16, bold: true, color: '#7F77DD' },
      h2: { fontSize: 14, bold: true, color: '#534AB7' },
      h3: { fontSize: 12, bold: true, color: '#26215C' },
      body: { fontSize: 11, lineHeight: 1.5 },
    },
    defaultStyle: { font: 'Roboto', fontSize: 11 },
    pageSize: 'A4',
    pageMargins: [60, 60, 60, 60] as [number, number, number, number],
  };
}

function parseInlineMarkdown(text: string): object[] {
  // Very basic bold/italic support for pdfmake
  const parts: object[] = [];
  const regex = /\*\*(.+?)\*\*|\*(.+?)\*/g;
  let lastIndex = 0;
  let match;

  while ((match = regex.exec(text)) !== null) {
    if (match.index > lastIndex) {
      parts.push({ text: text.slice(lastIndex, match.index) });
    }
    if (match[1]) {
      parts.push({ text: match[1], bold: true });
    } else if (match[2]) {
      parts.push({ text: match[2], italics: true });
    }
    lastIndex = regex.lastIndex;
  }

  if (lastIndex < text.length) {
    parts.push({ text: text.slice(lastIndex) });
  }

  return parts.length ? parts : [{ text }];
}

// ── DOCX export ───────────────────────────────────────────────────────────────

async function exportAsDocx(
  markdown: string,
  documentName: string,
  filename: string
): Promise<ExportResult> {
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel,
    AlignmentType, LevelFormat
  } = await import('docx');

  const lines = markdown.split('\n');
  const children: InstanceType<typeof Paragraph>[] = [];

  // Title
  children.push(
    new Paragraph({
      children: [new TextRun({ text: documentName, bold: true, size: 40 })],
      spacing: { after: 200 },
    })
  );
  children.push(
    new Paragraph({
      children: [new TextRun({
        text: `Generated by StudySummarizer · ${new Date().toLocaleDateString()}`,
        color: '888888',
        size: 18,
      })],
      spacing: { after: 400 },
    })
  );

  for (const line of lines) {
    if (line.startsWith('## ')) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun(line.slice(3))],
        spacing: { before: 300, after: 120 },
      }));
    } else if (line.startsWith('### ')) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_3,
        children: [new TextRun(line.slice(4))],
        spacing: { before: 200, after: 80 },
      }));
    } else if (line.startsWith('# ')) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun(line.slice(2))],
        spacing: { before: 400, after: 160 },
      }));
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      children.push(new Paragraph({
        numbering: { reference: 'bullets', level: 0 },
        children: [new TextRun(line.slice(2))],
      }));
    } else if (line.trim()) {
      children.push(new Paragraph({
        children: [new TextRun({ text: line })],
        spacing: { after: 120 },
      }));
    }
  }

  const doc = new Document({
    numbering: {
      config: [{
        reference: 'bullets',
        levels: [{
          level: 0,
          format: LevelFormat.BULLET,
          text: '•',
          alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } },
        }],
      }],
    },
    styles: {
      default: { document: { run: { font: 'Calibri', size: 24 } } },
      paragraphStyles: [
        {
          id: 'Heading1', name: 'Heading 1',
          run: { size: 36, bold: true, color: '534AB7', font: 'Calibri' },
          paragraph: { spacing: { before: 400, after: 160 }, outlineLevel: 0 },
        },
        {
          id: 'Heading2', name: 'Heading 2',
          run: { size: 28, bold: true, color: '534AB7', font: 'Calibri' },
          paragraph: { spacing: { before: 300, after: 120 }, outlineLevel: 1 },
        },
        {
          id: 'Heading3', name: 'Heading 3',
          run: { size: 24, bold: true, color: '26215C', font: 'Calibri' },
          paragraph: { spacing: { before: 200, after: 80 }, outlineLevel: 2 },
        },
      ],
    },
    sections: [{
      properties: {
        page: {
          size: { width: 12240, height: 15840 },
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
        },
      },
      children,
    }],
  });

  const buffer = await Packer.toBuffer(doc);
  return {
    buffer,
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    filename,
  };
}

// ── Markdown export ───────────────────────────────────────────────────────────

async function exportAsMarkdown(
  markdown: string,
  filename: string
): Promise<ExportResult> {
  const content = `# StudySummarizer Export\n\n_Generated: ${new Date().toLocaleString()}_\n\n---\n\n${markdown}`;
  return {
    buffer: Buffer.from(content, 'utf-8'),
    mimeType: 'text/markdown',
    filename,
  };
}

// ── Plain text export ─────────────────────────────────────────────────────────

async function exportAsText(
  markdown: string,
  filename: string
): Promise<ExportResult> {
  // Strip markdown syntax for plain text
  const text = markdown
    .replace(/#{1,6}\s+/g, '')
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/`(.+?)`/g, '$1');

  const content = `StudySummarizer Export\nGenerated: ${new Date().toLocaleString()}\n${'─'.repeat(40)}\n\n${text}`;
  return {
    buffer: Buffer.from(content, 'utf-8'),
    mimeType: 'text/plain',
    filename,
  };
}

// ── Utils ─────────────────────────────────────────────────────────────────────

function sanitizeFilename(name: string): string {
  return name
    .replace(/\.[^.]+$/, '')       // remove extension
    .replace(/[^a-zA-Z0-9_\-]/g, '_')
    .slice(0, 50);
}
